#!/bin/sh
[ -n "$HUSKY_SKIP_HOOKS" ] && exit 0

. "$(dirname "$0")/_/husky.sh"

export FORCE_COLOR=1;

echo "> lint for web";
yarn workspace web lint-staged -p false

echo "> lint for main";
yarn workspace main lint-staged -p false
